[build]
  base = "."
  command = "npm run build:client"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

# Proxy API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://studyspot-api.onrender.com/api/:splat"
  status = 200
  force = true

# Always route to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 